baseURL = 'http://tl.neocities.org/'
languageCode = 'en-us'
title = 'Travis Luckenbaugh'

[permalinks]
  posts = '/:year/:month/:title/'
  tdp = '/tdp/:title/'
  tools = '/tools/:title/'
  wiki = '/w/:title'

[markup.goldmark]
  extensions.typographer = false
  renderer.unsafe = true

[markup.highlight]
  style = "github-dark"

[[cascade]]
  [cascade._build]
    list = "never"
  [cascade._target]
    path = "{/wiki/**,/tdp/**}"